name: Build and release

on:
  push:
    tags:
      - '*.*.*-beta-*'
      - '*.*.*'

# We must only run one release workflow at a time to prevent corrupting
# our release artifacts.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false